using Accounts.Api.Data;
using Accounts.Api.Entities;
using Accounts.Api.Services;
using Microsoft.EntityFrameworkCore;

namespace Accounts.Api.Endpoints;

public static class AdjustmentEndpoints
{
    public static void MapAdjustmentEndpoints(this WebApplication app)
    {
        var basePath = "/api/companies/{companyId:int}/periods/{periodId:int}/adjustments";
        var group = app.MapGroup(basePath).WithTags("Adjustments");

        // List all adjustments
        group.MapGet("/", async (int companyId, int periodId, AccountsDbContext db,
            bool? approved, bool? isAuto) =>
        {
            var query = db.Adjustments
                .Include(a => a.DebitCategory)
                .Include(a => a.CreditCategory)
                .Where(a => a.PeriodId == periodId);

            if (approved == true)
                query = query.Where(a => a.ApprovedAt != null);
            else if (approved == false)
                query = query.Where(a => a.ApprovedAt == null);

            if (isAuto.HasValue)
                query = query.Where(a => a.IsAuto == isAuto.Value);

            return await query
                .OrderBy(a => a.IsAuto ? 0 : 1)
                .ThenBy(a => a.CreatedAt)
                .ToListAsync();
        });

        // Generate auto adjustments
        group.MapPost("/generate", async (int companyId, int periodId, AdjustmentService service) =>
        {
            try
            {
                var result = await service.GenerateAutoAdjustmentsAsync(periodId);
                return Results.Ok(result);
            }
            catch (InvalidOperationException ex)
            {
                return Results.BadRequest(new { error = ex.Message });
            }
        });

        // Create manual adjustment
        group.MapPost("/", async (int companyId, int periodId, Adjustment input, AccountsDbContext db, AuditService audit) =>
        {
            input.PeriodId = periodId;
            input.IsAuto = false;
            input.Source = AdjustmentSource.Manual;
            db.Adjustments.Add(input);
            await db.SaveChangesAsync();
            await audit.LogAsync(companyId, periodId, "Adjustment", input.Id, "Created", newValue: new { input.Description, input.Amount });
            return Results.Created($"{basePath}/{input.Id}", input);
        });

        // Update adjustment
        group.MapPut("/{id:int}", async (int companyId, int periodId, int id, Adjustment input, AccountsDbContext db) =>
        {
            var item = await db.Adjustments.FirstOrDefaultAsync(a => a.Id == id && a.PeriodId == periodId);
            if (item == null) return Results.NotFound();
            item.Description = input.Description;
            item.DebitCategoryId = input.DebitCategoryId;
            item.CreditCategoryId = input.CreditCategoryId;
            item.Amount = input.Amount;
            item.Reason = input.Reason;
            item.LegalBasis = input.LegalBasis;
            item.ImpactOnProfit = input.ImpactOnProfit;
            item.ImpactOnAssets = input.ImpactOnAssets;
            await db.SaveChangesAsync();
            return Results.Ok(item);
        });

        // Approve adjustment
        group.MapPost("/{id:int}/approve", async (int companyId, int periodId, int id, ApprovalInput input, AccountsDbContext db, AuditService audit) =>
        {
            var item = await db.Adjustments.FirstOrDefaultAsync(a => a.Id == id && a.PeriodId == periodId);
            if (item == null) return Results.NotFound();
            item.ApprovedBy = input.ApprovedBy;
            item.ApprovedAt = DateTime.UtcNow;
            await db.SaveChangesAsync();
            await audit.LogAsync(companyId, periodId, "Adjustment", id, "Approved", newValue: new { item.Description, input.ApprovedBy });
            return Results.Ok(item);
        });

        // Delete adjustment
        group.MapDelete("/{id:int}", async (int companyId, int periodId, int id, AccountsDbContext db) =>
        {
            var item = await db.Adjustments.FirstOrDefaultAsync(a => a.Id == id && a.PeriodId == periodId);
            if (item == null) return Results.NotFound();
            db.Adjustments.Remove(item);
            await db.SaveChangesAsync();
            return Results.NoContent();
        });

        // Adjustment summary
        group.MapGet("/summary", async (int companyId, int periodId, AccountsDbContext db) =>
        {
            var adjustments = await db.Adjustments.Where(a => a.PeriodId == periodId).ToListAsync();
            return Results.Ok(new
            {
                autoGenerated = adjustments.Count(a => a.IsAuto),
                manual = adjustments.Count(a => !a.IsAuto),
                pendingApproval = adjustments.Count(a => a.ApprovedAt == null),
                approved = adjustments.Count(a => a.ApprovedAt != null),
                totalImpactOnProfit = adjustments.Sum(a => a.ImpactOnProfit),
                totalImpactOnAssets = adjustments.Sum(a => a.ImpactOnAssets)
            });
        });

        // Audit log
        var auditGroup = app.MapGroup("/api/companies/{companyId:int}/audit-log").WithTags("Audit");

        auditGroup.MapGet("/", async (int companyId, AccountsDbContext db, int? periodId, int? page, int? pageSize) =>
        {
            var query = db.AuditLogs.Where(a => a.CompanyId == companyId);
            if (periodId.HasValue) query = query.Where(a => a.PeriodId == periodId);
            var total = await query.CountAsync();
            var items = await query
                .OrderByDescending(a => a.Timestamp)
                .Skip(((page ?? 1) - 1) * (pageSize ?? 50))
                .Take(pageSize ?? 50)
                .ToListAsync();
            return Results.Ok(new { total, items });
        });
    }
}

public record ApprovalInput(string ApprovedBy);
