// <auto-generated />
using System;
using Accounts.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accounts.Api.Data.Migrations
{
    [DbContext(typeof(AccountsDbContext))]
    [Migration("20260403172728_Phase5_CharitySorp")]
    partial class Phase5_CharitySorp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accounts.Api.Entities.AccountCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("TaxTreatment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ParentId");

                    b.ToTable("account_categories", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.AccountingPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GoingConcernConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("GoingConcernNote")
                        .HasColumnType("text");

                    b.Property<bool>("IsFirstYear")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("MemberAuditNoticeDate")
                        .HasColumnType("date");

                    b.Property<bool>("MemberAuditNoticeReceived")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "PeriodEnd")
                        .IsUnique();

                    b.ToTable("accounting_periods", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.Adjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int?>("CreditCategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("DebitCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ImpactOnAssets")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImpactOnProfit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAuto")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalBasis")
                        .HasColumnType("text");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreditCategoryId");

                    b.HasIndex("DebitCategoryId");

                    b.HasIndex("PeriodId");

                    b.ToTable("adjustments", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValueJson")
                        .HasColumnType("text");

                    b.Property<string>("OldValueJson")
                        .HasColumnType("text");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("CompanyId", "Timestamp");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Iban")
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("OpeningBalanceDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("bank_accounts", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.CharityInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CharitableObjectives")
                        .HasColumnType("text");

                    b.Property<string>("CharityNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CharityType")
                        .HasColumnType("text");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("GovernanceCodeCompliant")
                        .HasColumnType("boolean");

                    b.Property<string>("GovernanceCodeNote")
                        .HasColumnType("text");

                    b.Property<decimal>("GrossIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasInternationalTransfers")
                        .HasColumnType("boolean");

                    b.Property<string>("InternationalTransferDetails")
                        .HasColumnType("text");

                    b.Property<string>("PrincipalActivities")
                        .HasColumnType("text");

                    b.Property<int>("SorpTier")
                        .HasColumnType("integer");

                    b.Property<string>("TrusteeExpensesDetails")
                        .HasColumnType("text");

                    b.Property<decimal>("TrusteeRemunerationAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TrusteeRemunerationPaid")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("charity_infos", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArdMonth")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CroNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("FinancialYearStartMonth")
                        .HasColumnType("integer");

                    b.Property<bool>("HasBorrowings")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasDirectorLoans")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasStock")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("IncorporationDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCharitableOrganisation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCreditInstitution")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDormant")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmployer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGroupMember")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHolding")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInsuranceUndertaking")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInvestment")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsListedSecurities")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPensionFund")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubsidiary")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrading")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVatRegistered")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("OwnsAssets")
                        .HasColumnType("boolean");

                    b.Property<string>("RegisteredOfficeAddress1")
                        .HasColumnType("text");

                    b.Property<string>("RegisteredOfficeAddress2")
                        .HasColumnType("text");

                    b.Property<string>("RegisteredOfficeCity")
                        .HasColumnType("text");

                    b.Property<string>("RegisteredOfficeCounty")
                        .HasColumnType("text");

                    b.Property<string>("RegisteredOfficeEircode")
                        .HasColumnType("text");

                    b.Property<string>("TaxReference")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TradingName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CroNumber")
                        .IsUnique()
                        .HasFilter("\"CroNumber\" IS NOT NULL");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.CompanyOfficer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("AppointedDate")
                        .HasColumnType("date");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateOnly?>("ResignedDate")
                        .HasColumnType("date");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("company_officers", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.ContingentLiability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("EstimatedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Likelihood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nature")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("contingent_liabilities", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.Creditor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("DueWithinYear")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("creditors", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.CroFilingPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PdfPath")
                        .HasColumnType("text");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId")
                        .IsUnique();

                    b.ToTable("cro_filing_packages", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.Debtor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("debtors", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.DepreciationEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Charge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ClosingNbv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpeningNbv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("AssetId", "PeriodId")
                        .IsUnique();

                    b.ToTable("depreciation_entries", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.DirectorLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Advances")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("InterestCharged")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsDocumented")
                        .HasColumnType("boolean");

                    b.Property<string>("LoanTerms")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("MaxBalanceDuringYear")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Repayments")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("PeriodId");

                    b.ToTable("director_loans", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.Dividend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("DateDeclared")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DatePaid")
                        .HasColumnType("date");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("dividends", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.FilingDeadline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeadlineType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FiledDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsLate")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("CompanyId", "PeriodId", "DeadlineType")
                        .IsUnique();

                    b.ToTable("filing_deadlines", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.FilingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("DaysLate")
                        .HasColumnType("integer");

                    b.Property<string>("DeadlineType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FiledDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PenaltyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("CompanyId", "DueDate");

                    b.ToTable("filing_histories", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.FilingRegime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AuditExempt")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanFileAbridged")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUseMicro")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DeterminedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElectedRegime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredNotesJson")
                        .HasColumnType("text");

                    b.Property<string>("RequiredStatementsJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId")
                        .IsUnique();

                    b.ToTable("filing_regimes", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.FixedAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AcquisitionDate")
                        .HasColumnType("date");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DepreciationMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DisposalDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("DisposalProceeds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("UsefulLifeYears")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("fixed_assets", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.FundBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FundName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FundType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GainsLosses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IncomingResources")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ResourcesExpended")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Transfers")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("fund_balances", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("integer");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.ImportedTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BankAccountId")
                        .HasColumnType("integer");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("ImportBatchId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDuplicate")
                        .HasColumnType("boolean");

                    b.Property<bool>("ManualOverride")
                        .HasColumnType("boolean");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("PeriodId");

                    b.HasIndex("BankAccountId", "Date", "Amount", "Description")
                        .HasDatabaseName("ix_transaction_duplicate_check");

                    b.ToTable("imported_transactions", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("ValuationMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("inventories", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DueAfterYear")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DueWithinYear")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsDirectorLoan")
                        .HasColumnType("boolean");

                    b.Property<string>("Lender")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("loans", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.NotesDisclosure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<bool>("IsIncluded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("NoteNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId", "NoteNumber")
                        .IsUnique();

                    b.ToTable("notes_disclosures", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.PayrollSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("EmployerPrsi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossWages")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PensionContributions")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<int>("StaffCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId")
                        .IsUnique();

                    b.ToTable("payroll_summaries", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.PostBalanceSheetEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionRequired")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("FinancialImpact")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAdjusting")
                        .HasColumnType("boolean");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("post_balance_sheet_events", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.RelatedPartyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BalanceOwed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Terms")
                        .HasColumnType("text");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("related_party_transactions", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DataJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.RevenueFilingPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ct1DataJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IxbrlPath")
                        .HasColumnType("text");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId")
                        .IsUnique();

                    b.ToTable("revenue_filing_packages", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.ShareCapital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFullyPaid")
                        .HasColumnType("boolean");

                    b.Property<decimal>("NominalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumberIssued")
                        .HasColumnType("integer");

                    b.Property<string>("ShareClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TotalValue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("share_capitals", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.SizeClassification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvgEmployees")
                        .HasColumnType("integer");

                    b.Property<decimal>("BalanceSheetTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CalculatedClass")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExclusionFlagsJson")
                        .HasColumnType("text");

                    b.Property<string>("OverrideClass")
                        .HasColumnType("text");

                    b.Property<string>("OverrideReason")
                        .HasColumnType("text");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("PriorYearClass")
                        .HasColumnType("text");

                    b.Property<string>("QualificationNotes")
                        .HasColumnType("text");

                    b.Property<decimal>("Turnover")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId")
                        .IsUnique();

                    b.ToTable("size_classifications", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.TaxBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Liability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Paid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer");

                    b.Property<string>("TaxType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId", "TaxType")
                        .IsUnique();

                    b.ToTable("tax_balances", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.TransactionRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.ToTable("transaction_rules", (string)null);
                });

            modelBuilder.Entity("Accounts.Api.Entities.AccountCategory", b =>
                {
                    b.HasOne("Accounts.Api.Entities.Company", "Company")
                        .WithMany("Categories")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Accounts.Api.Entities.AccountCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Accounts.Api.Entities.AccountingPeriod", b =>
                {
                    b.HasOne("Accounts.Api.Entities.Company", "Company")
                        .WithMany("Periods")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Accounts.Api.Entities.Adjustment", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountCategory", "CreditCategory")
                        .WithMany()
                        .HasForeignKey("CreditCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accounts.Api.Entities.AccountCategory", "DebitCategory")
                        .WithMany()
                        .HasForeignKey("DebitCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("Adjustments")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCategory");

                    b.Navigation("DebitCategory");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.BankAccount", b =>
                {
                    b.HasOne("Accounts.Api.Entities.Company", "Company")
                        .WithMany("BankAccounts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Accounts.Api.Entities.CharityInfo", b =>
                {
                    b.HasOne("Accounts.Api.Entities.Company", "Company")
                        .WithOne("CharityInfo")
                        .HasForeignKey("Accounts.Api.Entities.CharityInfo", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Accounts.Api.Entities.CompanyOfficer", b =>
                {
                    b.HasOne("Accounts.Api.Entities.Company", "Company")
                        .WithMany("Officers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Accounts.Api.Entities.ContingentLiability", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("ContingentLiabilities")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.Creditor", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("Creditors")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.CroFilingPackage", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithOne("CroFilingPackage")
                        .HasForeignKey("Accounts.Api.Entities.CroFilingPackage", "PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.Debtor", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("Debtors")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.DepreciationEntry", b =>
                {
                    b.HasOne("Accounts.Api.Entities.FixedAsset", "Asset")
                        .WithMany("DepreciationEntries")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("DepreciationEntries")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.DirectorLoan", b =>
                {
                    b.HasOne("Accounts.Api.Entities.CompanyOfficer", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("DirectorLoans")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.Dividend", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("Dividends")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.FilingDeadline", b =>
                {
                    b.HasOne("Accounts.Api.Entities.Company", "Company")
                        .WithMany("FilingDeadlines")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("FilingDeadlines")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.FilingHistory", b =>
                {
                    b.HasOne("Accounts.Api.Entities.Company", "Company")
                        .WithMany("FilingHistories")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.FilingRegime", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithOne("FilingRegime")
                        .HasForeignKey("Accounts.Api.Entities.FilingRegime", "PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.FixedAsset", b =>
                {
                    b.HasOne("Accounts.Api.Entities.Company", "Company")
                        .WithMany("FixedAssets")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Accounts.Api.Entities.FundBalance", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("FundBalances")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.ImportBatch", b =>
                {
                    b.HasOne("Accounts.Api.Entities.BankAccount", "BankAccount")
                        .WithMany("ImportBatches")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");
                });

            modelBuilder.Entity("Accounts.Api.Entities.ImportedTransaction", b =>
                {
                    b.HasOne("Accounts.Api.Entities.BankAccount", "BankAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accounts.Api.Entities.AccountCategory", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accounts.Api.Entities.ImportBatch", "ImportBatch")
                        .WithMany("Transactions")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("Transactions")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BankAccount");

                    b.Navigation("Category");

                    b.Navigation("ImportBatch");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.Inventory", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("Inventories")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.Loan", b =>
                {
                    b.HasOne("Accounts.Api.Entities.Company", "Company")
                        .WithMany("Loans")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Accounts.Api.Entities.NotesDisclosure", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("NotesDisclosures")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.PayrollSummary", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithOne("PayrollSummary")
                        .HasForeignKey("Accounts.Api.Entities.PayrollSummary", "PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.PostBalanceSheetEvent", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("PostBalanceSheetEvents")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.RelatedPartyTransaction", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("RelatedPartyTransactions")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.Report", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("Reports")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.RevenueFilingPackage", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithOne("RevenueFilingPackage")
                        .HasForeignKey("Accounts.Api.Entities.RevenueFilingPackage", "PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.ShareCapital", b =>
                {
                    b.HasOne("Accounts.Api.Entities.Company", "Company")
                        .WithMany("ShareCapitals")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Accounts.Api.Entities.SizeClassification", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithOne("SizeClassification")
                        .HasForeignKey("Accounts.Api.Entities.SizeClassification", "PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.TaxBalance", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountingPeriod", "Period")
                        .WithMany("TaxBalances")
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Period");
                });

            modelBuilder.Entity("Accounts.Api.Entities.TransactionRule", b =>
                {
                    b.HasOne("Accounts.Api.Entities.AccountCategory", "Category")
                        .WithMany("Rules")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accounts.Api.Entities.Company", "Company")
                        .WithMany("TransactionRules")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Accounts.Api.Entities.AccountCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Rules");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Accounts.Api.Entities.AccountingPeriod", b =>
                {
                    b.Navigation("Adjustments");

                    b.Navigation("ContingentLiabilities");

                    b.Navigation("Creditors");

                    b.Navigation("CroFilingPackage");

                    b.Navigation("Debtors");

                    b.Navigation("DepreciationEntries");

                    b.Navigation("DirectorLoans");

                    b.Navigation("Dividends");

                    b.Navigation("FilingDeadlines");

                    b.Navigation("FilingRegime");

                    b.Navigation("FundBalances");

                    b.Navigation("Inventories");

                    b.Navigation("NotesDisclosures");

                    b.Navigation("PayrollSummary");

                    b.Navigation("PostBalanceSheetEvents");

                    b.Navigation("RelatedPartyTransactions");

                    b.Navigation("Reports");

                    b.Navigation("RevenueFilingPackage");

                    b.Navigation("SizeClassification");

                    b.Navigation("TaxBalances");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Accounts.Api.Entities.BankAccount", b =>
                {
                    b.Navigation("ImportBatches");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Accounts.Api.Entities.Company", b =>
                {
                    b.Navigation("BankAccounts");

                    b.Navigation("Categories");

                    b.Navigation("CharityInfo");

                    b.Navigation("FilingDeadlines");

                    b.Navigation("FilingHistories");

                    b.Navigation("FixedAssets");

                    b.Navigation("Loans");

                    b.Navigation("Officers");

                    b.Navigation("Periods");

                    b.Navigation("ShareCapitals");

                    b.Navigation("TransactionRules");
                });

            modelBuilder.Entity("Accounts.Api.Entities.FixedAsset", b =>
                {
                    b.Navigation("DepreciationEntries");
                });

            modelBuilder.Entity("Accounts.Api.Entities.ImportBatch", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
