using Accounts.Api.Data;
using Accounts.Api.Entities;
using Microsoft.EntityFrameworkCore;

namespace Accounts.Api.Services;

public class AdjustmentService(AccountsDbContext db)
{
    public record AdjustmentSummary(int AutoGenerated, int Manual, int PendingApproval, int Approved, decimal TotalImpactOnProfit, decimal TotalImpactOnAssets);

    public async Task<AdjustmentSummary> GenerateAutoAdjustmentsAsync(int periodId)
    {
        var period = await db.AccountingPeriods
            .Include(p => p.Company)
            .FirstOrDefaultAsync(p => p.Id == periodId)
            ?? throw new InvalidOperationException($"Period {periodId} not found");

        var companyId = period.CompanyId;

        // Remove previous auto-adjustments for this period
        var existingAuto = await db.Adjustments.Where(a => a.PeriodId == periodId && a.IsAuto).ToListAsync();
        db.Adjustments.RemoveRange(existingAuto);

        var adjustments = new List<Adjustment>();

        // 1. Depreciation charges
        var assets = await db.FixedAssets
            .Where(a => a.CompanyId == companyId && a.DisposalDate == null)
            .ToListAsync();

        foreach (var asset in assets)
        {
            if (asset.UsefulLifeYears <= 0) continue;

            decimal annualCharge;
            decimal openingNbv = asset.Cost;

            // Check for prior depreciation
            var lastEntry = await db.DepreciationEntries
                .Where(d => d.AssetId == asset.Id)
                .OrderByDescending(d => d.Period.PeriodEnd)
                .FirstOrDefaultAsync();

            if (lastEntry != null)
                openingNbv = lastEntry.ClosingNbv;

            if (openingNbv <= 0) continue;

            if (asset.DepreciationMethod == DepreciationMethod.StraightLine)
                annualCharge = asset.Cost / asset.UsefulLifeYears;
            else // Reducing balance (typically 25%)
                annualCharge = openingNbv * (1m / asset.UsefulLifeYears);

            // Don't depreciate below zero
            annualCharge = Math.Min(annualCharge, openingNbv);
            annualCharge = Math.Round(annualCharge, 2);

            // Create/update depreciation entry
            var depEntry = await db.DepreciationEntries
                .FirstOrDefaultAsync(d => d.AssetId == asset.Id && d.PeriodId == periodId);
            if (depEntry == null)
            {
                depEntry = new DepreciationEntry { AssetId = asset.Id, PeriodId = periodId };
                db.DepreciationEntries.Add(depEntry);
            }
            depEntry.OpeningNbv = openingNbv;
            depEntry.Charge = annualCharge;
            depEntry.ClosingNbv = openingNbv - annualCharge;

            adjustments.Add(new Adjustment
            {
                PeriodId = periodId,
                Description = $"Depreciation — {asset.Name} ({asset.Category})",
                Amount = annualCharge,
                Source = AdjustmentSource.Auto,
                Reason = $"{asset.DepreciationMethod} over {asset.UsefulLifeYears} years",
                LegalBasis = "FRS 102 Section 17 / FRS 105",
                ImpactOnProfit = -annualCharge,
                ImpactOnAssets = -annualCharge,
                IsAuto = true,
                CreatedBy = "System"
            });
        }

        // 2. Prepayment adjustments (debtors of type Prepayment represent future benefit)
        var prepayments = await db.Debtors
            .Where(d => d.PeriodId == periodId && d.Type == DebtorType.Prepayment)
            .ToListAsync();

        foreach (var prep in prepayments)
        {
            adjustments.Add(new Adjustment
            {
                PeriodId = periodId,
                Description = $"Prepayment — {prep.Name}",
                Amount = prep.Amount,
                Source = AdjustmentSource.Auto,
                Reason = "Expense paid in advance, recognised as current asset",
                LegalBasis = "FRS 102 Section 2 / Accruals concept",
                ImpactOnProfit = prep.Amount, // reduces expense = increases profit
                ImpactOnAssets = prep.Amount,
                IsAuto = true,
                CreatedBy = "System"
            });
        }

        // 3. Accrual adjustments (creditors of type Accrual)
        var accruals = await db.Creditors
            .Where(c => c.PeriodId == periodId && c.Type == CreditorType.Accrual)
            .ToListAsync();

        foreach (var acc in accruals)
        {
            adjustments.Add(new Adjustment
            {
                PeriodId = periodId,
                Description = $"Accrual — {acc.Name}",
                Amount = acc.Amount,
                Source = AdjustmentSource.Auto,
                Reason = "Expense incurred but not yet invoiced/paid",
                LegalBasis = "FRS 102 Section 2 / Accruals concept",
                ImpactOnProfit = -acc.Amount,
                ImpactOnAssets = 0,
                IsAuto = true,
                CreatedBy = "System"
            });
        }

        // 4. Corporation tax provision
        var corpTax = await db.TaxBalances
            .FirstOrDefaultAsync(t => t.PeriodId == periodId && t.TaxType == TaxType.CorporationTax);

        if (corpTax != null && corpTax.Liability > 0)
        {
            adjustments.Add(new Adjustment
            {
                PeriodId = periodId,
                Description = "Corporation tax provision",
                Amount = corpTax.Liability,
                Source = AdjustmentSource.Auto,
                Reason = $"Estimated corporation tax liability: €{corpTax.Liability:N2}",
                LegalBasis = "FRS 102 Section 29 / Corporation Tax Acts",
                ImpactOnProfit = -corpTax.Liability,
                ImpactOnAssets = 0,
                IsAuto = true,
                CreatedBy = "System"
            });
        }

        // 5. Stock/Inventory adjustment (if closing stock entered)
        var inventories = await db.Inventories
            .Where(i => i.PeriodId == periodId)
            .ToListAsync();

        var closingStockValue = inventories.Sum(i => i.Value);
        if (closingStockValue > 0)
        {
            adjustments.Add(new Adjustment
            {
                PeriodId = periodId,
                Description = "Closing stock / inventory recognition",
                Amount = closingStockValue,
                Source = AdjustmentSource.Auto,
                Reason = $"Closing stock valued at €{closingStockValue:N2} ({string.Join(", ", inventories.Select(i => i.ValuationMethod.ToString()).Distinct())})",
                LegalBasis = "FRS 102 Section 13 / Lower of cost and NRV",
                ImpactOnProfit = closingStockValue,
                ImpactOnAssets = closingStockValue,
                IsAuto = true,
                CreatedBy = "System"
            });
        }

        // 6. Retained earnings roll-forward
        var priorPeriod = await db.AccountingPeriods
            .Where(p => p.CompanyId == companyId && p.PeriodEnd < period.PeriodStart)
            .OrderByDescending(p => p.PeriodEnd)
            .FirstOrDefaultAsync();

        if (priorPeriod != null)
        {
            adjustments.Add(new Adjustment
            {
                PeriodId = periodId,
                Description = "Retained earnings — brought forward from prior period",
                Amount = 0, // Will be computed from prior period P&L
                Source = AdjustmentSource.Auto,
                Reason = $"Carried forward from period ending {priorPeriod.PeriodEnd:yyyy-MM-dd}",
                LegalBasis = "Companies Act 2014 — Capital maintenance",
                ImpactOnProfit = 0,
                ImpactOnAssets = 0,
                IsAuto = true,
                CreatedBy = "System"
            });
        }

        db.Adjustments.AddRange(adjustments);
        await db.SaveChangesAsync();

        // Calculate summary
        var allAdjustments = await db.Adjustments.Where(a => a.PeriodId == periodId).ToListAsync();
        return new AdjustmentSummary(
            allAdjustments.Count(a => a.IsAuto),
            allAdjustments.Count(a => !a.IsAuto),
            allAdjustments.Count(a => a.ApprovedAt == null),
            allAdjustments.Count(a => a.ApprovedAt != null),
            allAdjustments.Sum(a => a.ImpactOnProfit),
            allAdjustments.Sum(a => a.ImpactOnAssets)
        );
    }
}
