using Accounts.Api.Data;
using Accounts.Api.Entities;
using Microsoft.EntityFrameworkCore;

namespace Accounts.Api.Services;

public class AdjustmentService(AccountsDbContext db)
{
    // Marks Accrual creditor rows the engine created for loan interest, so they can be refreshed on
    // regeneration without touching creditors the user entered.
    private const string AutoLoanInterestMarker = "[auto:loan-interest]";

    public record AdjustmentSummary(int AutoGenerated, int Manual, int PendingApproval, int Approved, decimal TotalImpactOnProfit, decimal TotalImpactOnAssets);

    public async Task<AdjustmentSummary> GenerateAutoAdjustmentsAsync(int companyId, int periodId)
    {
        var period = await db.AccountingPeriods
            .Include(p => p.Company)
            .FirstOrDefaultAsync(p => p.Id == periodId && p.CompanyId == companyId)
            ?? throw new ResourceNotFoundException($"Period {periodId} not found");

        // accounting-depreciation-regeneration-order: regenerating an earlier period rolls new closing
        // NBVs (and capital-allowance claim counts) forward, so it would silently drift a later period
        // that is already Finalised or Filed and could push cumulative depreciation over cost. Block the
        // regeneration rather than corrupt a locked period; the later period must be reopened first.
        var lockedLaterPeriodExists = await db.AccountingPeriods.AnyAsync(p => p.CompanyId == companyId
            && p.PeriodEnd > period.PeriodEnd
            && (p.Status == PeriodStatus.Finalised || p.Status == PeriodStatus.Filed));
        if (lockedLaterPeriodExists)
            throw new BusinessRuleException(
                "Cannot regenerate adjustments for this period because a later period is already finalised or filed. Reopen the later period first.");

        // Remove previous auto-adjustments for this period
        var existingAuto = await db.Adjustments.Where(a => a.PeriodId == periodId && a.IsAuto).ToListAsync();
        db.Adjustments.RemoveRange(existingAuto);

        // Loan interest accrual (BL-07). Recognise interest charged on outstanding loans for the
        // period. Stored as an Accrual creditor (so it shows as a liability on the balance sheet) and
        // turned into an interest expense by the accruals section below, keeping the sheet balanced.
        // It is a proposed working-paper adjustment the reviewer approves/edits — refresh the prior
        // auto set first so regeneration is idempotent. (Estimated on the closing balance; see note.)
        var existingAutoInterest = await db.Creditors
            .Where(c => c.PeriodId == periodId && c.Notes == AutoLoanInterestMarker)
            .ToListAsync();
        db.Creditors.RemoveRange(existingAutoInterest);
        await db.SaveChangesAsync();

        var loanPeriodFraction = PeriodYearFraction(period.PeriodStart, period.PeriodEnd);
        var interestBearingLoans = await db.Loans
            .Where(l => l.CompanyId == companyId
                && l.InterestRate > 0
                && l.Balance > 0
                && l.DrawdownDate != null
                && l.DrawdownDate <= period.PeriodEnd)
            .ToListAsync();
        foreach (var loan in interestBearingLoans)
        {
            var interest = Math.Round(loan.Balance * loan.InterestRate / 100m * loanPeriodFraction, 2);
            if (interest <= 0) continue;
            db.Creditors.Add(new Creditor
            {
                PeriodId = periodId,
                Name = $"Loan interest — {loan.Lender}",
                Amount = interest,
                Type = CreditorType.Accrual,
                DueWithinYear = true,
                Notes = AutoLoanInterestMarker
            });
        }
        await db.SaveChangesAsync();

        var adjustments = new List<Adjustment>();
        var depreciationExpenseId = await GetOrCreateCategoryIdAsync(companyId, "7000", "Depreciation", AccountCategoryType.Expense, TaxTreatment.NonDeductible);
        var prepaymentId = await GetOrCreateCategoryIdAsync(companyId, "1200", "Prepayments", AccountCategoryType.Asset, TaxTreatment.Other);
        var inventoryId = await GetOrCreateCategoryIdAsync(companyId, "1000", "Stock / Inventory", AccountCategoryType.Asset, TaxTreatment.Other);
        var costOfSalesId = await GetOrCreateCategoryIdAsync(companyId, "5000", "Cost of Sales", AccountCategoryType.Expense, TaxTreatment.Deductible);
        var accrualsId = await GetOrCreateCategoryIdAsync(companyId, "2100", "Accruals", AccountCategoryType.Liability, TaxTreatment.Other);
        var corporationTaxChargeId = await GetOrCreateCategoryIdAsync(companyId, "8000", "Corporation Tax Charge", AccountCategoryType.Expense, TaxTreatment.NonDeductible);
        var corporationTaxPayableId = await GetOrCreateCategoryIdAsync(companyId, "2400", "Corporation Tax Payable", AccountCategoryType.Liability, TaxTreatment.Other);
        var dividendsPaidId = await GetOrCreateCategoryIdAsync(companyId, "3200", "Dividends Paid", AccountCategoryType.Equity, TaxTreatment.Other);
        var dividendsPayableId = await GetOrCreateCategoryIdAsync(companyId, "2800", "Dividends Payable", AccountCategoryType.Liability, TaxTreatment.Other);
        var bankControlId = await GetOrCreateCategoryIdAsync(companyId, "1400", "Bank Current Account", AccountCategoryType.Asset, TaxTreatment.Other);
        var disposalLossId = await GetOrCreateCategoryIdAsync(companyId, "7050", "Loss on Disposal of Fixed Assets", AccountCategoryType.Expense, TaxTreatment.NonDeductible);
        var disposalGainId = await GetOrCreateCategoryIdAsync(companyId, "9000", "Gain on Disposal of Fixed Assets", AccountCategoryType.Income, TaxTreatment.Other);

        var priorPeriod = await PeriodChronologyService
            .PriorPeriodQuery(db, companyId, period.PeriodStart)
            .FirstOrDefaultAsync();

        // Period-end working-capital journals are closing snapshots. Reverse the exact prior-period
        // postings before recognising this period's closing facts, so opening stock reaches cost of
        // sales and debtors/creditors/prepayments do not accumulate across periods.
        if (priorPeriod is not null)
        {
            var priorClosingJournals = await db.Adjustments
                .Where(a => a.PeriodId == priorPeriod.Id
                    && a.IsAuto
                    && a.Amount > 0
                    && a.DebitCategoryId != null
                    && a.CreditCategoryId != null)
                .OrderBy(a => a.Id)
                .ToListAsync();
            foreach (var prior in priorClosingJournals.Where(IsReversingBalanceJournal))
            {
                adjustments.Add(new Adjustment
                {
                    PeriodId = periodId,
                    Description = $"Opening reversal — {prior.Description}",
                    DebitCategoryId = prior.CreditCategoryId,
                    CreditCategoryId = prior.DebitCategoryId,
                    Amount = prior.Amount,
                    Source = AdjustmentSource.Auto,
                    Reason = $"Exact reversal of prior-period closing journal #{prior.Id}",
                    LegalBasis = prior.LegalBasis,
                    IsAuto = true,
                    CreatedBy = "System"
                });
            }
        }

        // 1. Depreciation charges
        var assets = await db.FixedAssets
            .Where(a => a.CompanyId == companyId
                && a.AcquisitionDate <= period.PeriodEnd
                && (a.DisposalDate == null || a.DisposalDate >= period.PeriodStart))
            .ToListAsync();

        foreach (var asset in assets)
        {
            if (asset.UsefulLifeYears <= 0) continue;

            decimal openingNbv = asset.Cost;

            // Check for prior depreciation
            var priorEntries = await db.DepreciationEntries
                .Where(d => d.AssetId == asset.Id && d.Period.PeriodEnd < period.PeriodStart)
                .OrderByDescending(d => d.Period.PeriodEnd)
                .ToListAsync();
            var lastEntry = priorEntries.FirstOrDefault();

            if (lastEntry != null)
                openingNbv = lastEntry.ClosingNbv;

            var residualValue = Math.Max(0m, Math.Min(asset.ResidualValue, asset.Cost));
            var depreciableOpening = Math.Max(0m, openingNbv - residualValue);
            decimal annualCharge;
            if (asset.DepreciationMethod == DepreciationMethod.StraightLine)
                annualCharge = (asset.Cost - residualValue) / asset.UsefulLifeYears;
            else // Reducing balance (typically 25%)
            {
                annualCharge = depreciableOpening * (1m / asset.UsefulLifeYears);
                // In the final year of the asset's useful life, write off the remaining book value so a
                // reducing-balance asset reaches its declared residual value by the end of its life.
                if (priorEntries.Count + 1 >= asset.UsefulLifeYears)
                    annualCharge = depreciableOpening;
            }

            var activeStart = asset.AcquisitionDate > period.PeriodStart ? asset.AcquisitionDate : period.PeriodStart;
            var activeEnd = asset.DisposalDate is { } disposal && disposal < period.PeriodEnd ? disposal : period.PeriodEnd;
            var activeFraction = activeEnd < activeStart ? 0m : ActualActualYearFraction(activeStart, activeEnd);
            var charge = Math.Round(Math.Min(annualCharge * activeFraction, depreciableOpening), 2);

            // Create/update depreciation entry
            var depEntry = await db.DepreciationEntries
                .FirstOrDefaultAsync(d => d.AssetId == asset.Id && d.PeriodId == periodId);
            if (depEntry == null)
            {
                depEntry = new DepreciationEntry { AssetId = asset.Id, PeriodId = periodId };
                db.DepreciationEntries.Add(depEntry);
            }
            depEntry.OpeningNbv = openingNbv;
            depEntry.Charge = charge;
            depEntry.ClosingNbv = openingNbv - charge;

            var assetCategoryId = await GetAssetCategoryIdAsync(companyId, asset.Category);
            if (charge > 0)
                adjustments.Add(new Adjustment
            {
                PeriodId = periodId,
                Description = $"Depreciation — {asset.Name} ({asset.Category})",
                DebitCategoryId = depreciationExpenseId,
                CreditCategoryId = assetCategoryId,
                Amount = charge,
                Source = AdjustmentSource.Auto,
                Reason = $"{asset.DepreciationMethod} over {asset.UsefulLifeYears} years; actual/actual active-period fraction {activeFraction:0.######}; residual value €{residualValue:N2}; fixed-asset source #{asset.Id}",
                LegalBasis = "FRS 102 Section 17 / FRS 105",
                ImpactOnProfit = -charge,
                ImpactOnAssets = -charge,
                IsAuto = true,
                CreatedBy = "System"
            });

            // The imported disposal receipt credits the asset account. This journal removes the
            // difference between proceeds and NBV and recognises the gain/loss, leaving the disposed
            // asset at nil in the ledger.
            if (asset.DisposalDate is { } disposalDate
                && disposalDate >= period.PeriodStart
                && disposalDate <= period.PeriodEnd
                && asset.DisposalProceeds is { } proceeds)
            {
                var difference = Math.Round(depEntry.ClosingNbv - proceeds, 2);
                if (difference > 0)
                {
                    adjustments.Add(new Adjustment
                    {
                        PeriodId = periodId,
                        Description = $"Fixed asset disposal loss — {asset.Name}",
                        DebitCategoryId = disposalLossId,
                        CreditCategoryId = assetCategoryId,
                        Amount = difference,
                        Source = AdjustmentSource.Auto,
                        Reason = $"NBV €{depEntry.ClosingNbv:N2} less proceeds €{proceeds:N2}; fixed-asset source #{asset.Id}",
                        LegalBasis = "FRS 102 Section 17 / FRS 105",
                        IsAuto = true,
                        CreatedBy = "System"
                    });
                }
                else if (difference < 0)
                {
                    adjustments.Add(new Adjustment
                    {
                        PeriodId = periodId,
                        Description = $"Fixed asset disposal gain — {asset.Name}",
                        DebitCategoryId = assetCategoryId,
                        CreditCategoryId = disposalGainId,
                        Amount = Math.Abs(difference),
                        Source = AdjustmentSource.Auto,
                        Reason = $"Proceeds €{proceeds:N2} less NBV €{depEntry.ClosingNbv:N2}; fixed-asset source #{asset.Id}",
                        LegalBasis = "FRS 102 Section 17 / FRS 105",
                        IsAuto = true,
                        CreatedBy = "System"
                    });
                }
            }
        }

        // 2. Prepayment adjustments (debtors of type Prepayment represent future benefit)
        var prepayments = await db.Debtors
            .Where(d => d.PeriodId == periodId && d.Type == DebtorType.Prepayment && d.Amount > 0)
            .ToListAsync();

        foreach (var prep in prepayments)
        {
            adjustments.Add(new Adjustment
            {
                PeriodId = periodId,
                Description = $"Prepayment — {prep.Name}",
                DebitCategoryId = prepaymentId,
                CreditCategoryId = await GetExpenseCategoryForDescriptionAsync(companyId, prep.Name),
                Amount = prep.Amount,
                Source = AdjustmentSource.Auto,
                Reason = "Expense paid in advance, recognised as current asset",
                LegalBasis = "FRS 102 Section 2 / Accruals concept",
                ImpactOnProfit = prep.Amount, // reduces expense = increases profit
                ImpactOnAssets = prep.Amount,
                IsAuto = true,
                CreatedBy = "System"
            });
        }

        // 2b. Trade debtor recognition (BL-01).
        // A trade debtor is income earned but not yet received in cash. The P&L is driven by bank
        // transactions, so it never sees that income; meanwhile the balance sheet already carries the
        // debtor as a current asset. Recognise the income (turnover) with the debtor as the contra so
        // the reserves side moves in step with the net-assets side and the sheet reconciles.
        // (Trade debtors only — Other debtors have an ambiguous contra and need a manual adjustment.)
        var tradeDebtorsId = await GetOrCreateCategoryIdAsync(companyId, "1100", "Trade Debtors", AccountCategoryType.Asset, TaxTreatment.Other);
        var salesId = await GetOrCreateCategoryIdAsync(companyId, "4000", "Sales / Revenue", AccountCategoryType.Income, TaxTreatment.Deductible);
        var tradeDebtors = await db.Debtors
            .Where(d => d.PeriodId == periodId && d.Type == DebtorType.Trade && d.Amount > 0)
            .ToListAsync();

        foreach (var debtor in tradeDebtors)
        {
            adjustments.Add(new Adjustment
            {
                PeriodId = periodId,
                Description = $"Trade debtor — {debtor.Name}",
                DebitCategoryId = tradeDebtorsId,
                CreditCategoryId = salesId,
                Amount = debtor.Amount,
                Source = AdjustmentSource.Auto,
                Reason = "Income earned but not yet received, recognised as turnover with a trade receivable",
                LegalBasis = "FRS 102 Section 23 / Accruals concept",
                ImpactOnProfit = debtor.Amount, // recognises income = increases profit
                ImpactOnAssets = debtor.Amount,
                IsAuto = true,
                CreatedBy = "System"
            });
        }

        // 3. Accrual adjustments (creditors of type Accrual)
        var accruals = await db.Creditors
            .Where(c => c.PeriodId == periodId && c.Type == CreditorType.Accrual && c.Amount > 0)
            .ToListAsync();

        foreach (var acc in accruals)
        {
            adjustments.Add(new Adjustment
            {
                PeriodId = periodId,
                Description = $"Accrual — {acc.Name}",
                DebitCategoryId = await GetExpenseCategoryForDescriptionAsync(companyId, acc.Name),
                CreditCategoryId = accrualsId,
                Amount = acc.Amount,
                Source = AdjustmentSource.Auto,
                Reason = "Expense incurred but not yet invoiced/paid",
                LegalBasis = "FRS 102 Section 2 / Accruals concept",
                ImpactOnProfit = -acc.Amount,
                ImpactOnAssets = 0,
                IsAuto = true,
                CreatedBy = "System"
            });
        }

        // 3b. Trade creditor recognition (BL-01).
        // A trade creditor is an expense incurred but not yet paid. Like an accrual, the cash-basis
        // P&L has not seen it, while the balance sheet already carries the payable. Recognise the
        // expense with the creditor as the contra so net assets and reserves stay reconciled.
        // (Trade creditors only — Other creditors have an ambiguous contra and need a manual entry.)
        var tradeCreditorsId = await GetOrCreateCategoryIdAsync(companyId, "2000", "Trade Creditors", AccountCategoryType.Liability, TaxTreatment.Other);
        var tradeCreditors = await db.Creditors
            .Where(c => c.PeriodId == periodId && c.Type == CreditorType.Trade && c.Amount > 0)
            .ToListAsync();

        foreach (var tradeCreditor in tradeCreditors)
        {
            adjustments.Add(new Adjustment
            {
                PeriodId = periodId,
                Description = $"Trade creditor — {tradeCreditor.Name}",
                DebitCategoryId = await GetExpenseCategoryForDescriptionAsync(companyId, tradeCreditor.Name),
                CreditCategoryId = tradeCreditorsId,
                Amount = tradeCreditor.Amount,
                Source = AdjustmentSource.Auto,
                Reason = "Expense incurred but not yet paid, recognised with a trade payable",
                LegalBasis = "FRS 102 Section 2 / Accruals concept",
                ImpactOnProfit = -tradeCreditor.Amount,
                ImpactOnAssets = 0,
                IsAuto = true,
                CreatedBy = "System"
            });
        }

        // 3c. Director loan reclassification (BL-07).
        // An overdrawn director's loan account (the director owes the company at year end) must be
        // presented as a receivable in its own right, not netted against amounts the company owes its
        // directors. Post a reclassification from the director-loan-account liability to a director's
        // loan receivable. P&L-neutral — it moves a balance between presentation accounts only.
        var directorLoanAccountId = await GetOrCreateCategoryIdAsync(companyId, "2500", "Director Loan Account", AccountCategoryType.Liability, TaxTreatment.Other);
        var directorLoanReceivableId = await GetOrCreateCategoryIdAsync(companyId, "1150", "Director Loan Account (debit)", AccountCategoryType.Asset, TaxTreatment.Other);
        var overdrawnDirectorLoans = await db.DirectorLoans
            .Include(d => d.Director)
            .Where(d => d.PeriodId == periodId
                && d.Period.CompanyId == companyId
                && d.ClosingBalance > 0
                && (d.CounterpartyType == DirectorLoanCounterpartyType.GroupCompany && d.DirectorId == null
                    || d.DirectorId != null && d.Director!.CompanyId == companyId))
            .ToListAsync();

        foreach (var dl in overdrawnDirectorLoans)
        {
            adjustments.Add(new Adjustment
            {
                PeriodId = periodId,
                Description = $"Director loan reclassification — {dl.CounterpartyName ?? dl.Director?.Name ?? $"Arrangement #{dl.Id}"}",
                DebitCategoryId = directorLoanReceivableId,
                CreditCategoryId = directorLoanAccountId,
                Amount = dl.ClosingBalance,
                Source = AdjustmentSource.Auto,
                Reason = $"Overdrawn director's loan account of €{dl.ClosingBalance:N2} presented as a receivable, not offset against creditors",
                LegalBasis = "Companies Act 2014 — loans to directors (s.236/s.239); FRS 102 Section 33",
                ImpactOnProfit = 0,
                ImpactOnAssets = dl.ClosingBalance,
                IsAuto = true,
                CreatedBy = "System"
            });
        }

        // 4. Corporation tax provision
        var corpTax = await db.TaxBalances
            .FirstOrDefaultAsync(t => t.PeriodId == periodId && t.TaxType == TaxType.CorporationTax);

        if (corpTax != null && corpTax.Liability > 0)
        {
            adjustments.Add(new Adjustment
            {
                PeriodId = periodId,
                Description = "Corporation tax provision",
                DebitCategoryId = corporationTaxChargeId,
                CreditCategoryId = corporationTaxPayableId,
                Amount = corpTax.Liability,
                Source = AdjustmentSource.Auto,
                Reason = $"Estimated corporation tax liability: €{corpTax.Liability:N2}",
                LegalBasis = "FRS 102 Section 29 / Corporation Tax Acts",
                ImpactOnProfit = -corpTax.Liability,
                ImpactOnAssets = 0,
                IsAuto = true,
                CreatedBy = "System"
            });
        }

        // 5. Stock/Inventory adjustment (if closing stock entered)
        var inventories = await db.Inventories
            .Where(i => i.PeriodId == periodId)
            .ToListAsync();

        var closingStockValue = inventories.Sum(i => i.Value);
        if (closingStockValue > 0)
        {
            adjustments.Add(new Adjustment
            {
                PeriodId = periodId,
                Description = "Closing stock / inventory recognition",
                DebitCategoryId = inventoryId,
                CreditCategoryId = costOfSalesId,
                Amount = closingStockValue,
                Source = AdjustmentSource.Auto,
                Reason = $"Closing stock valued at €{closingStockValue:N2} ({string.Join(", ", inventories.Select(i => i.ValuationMethod.ToString()).Distinct())})",
                LegalBasis = "FRS 102 Section 13 / Lower of cost and NRV",
                ImpactOnProfit = closingStockValue,
                ImpactOnAssets = closingStockValue,
                IsAuto = true,
                CreatedBy = "System"
            });
        }

        // Dividends are equity journals, not a second subtraction performed independently by
        // statements. Avoid duplicating a matched imported bank payment; otherwise the retained paid
        // date or declaration is the explicit year-end source for the balanced posting.
        var dividends = await db.Dividends
            .Where(d => d.PeriodId == periodId && d.Amount > 0)
            .OrderBy(d => d.Id)
            .ToListAsync();
        foreach (var dividend in dividends)
        {
            if (dividend.DatePaid is { } paidDate)
            {
                var matchedBankPosting = await db.ImportedTransactions.AnyAsync(t =>
                    t.PeriodId == periodId
                    && !t.IsDuplicate
                    && t.CategoryId == dividendsPaidId
                    && t.Date == paidDate
                    && t.Amount == -dividend.Amount);
                if (matchedBankPosting)
                    continue;

                adjustments.Add(new Adjustment
                {
                    PeriodId = periodId,
                    Description = $"Dividend paid — source #{dividend.Id}",
                    DebitCategoryId = dividendsPaidId,
                    CreditCategoryId = bankControlId,
                    Amount = dividend.Amount,
                    Source = AdjustmentSource.Auto,
                    Reason = $"Dividend payment retained with paid date {paidDate:yyyy-MM-dd}",
                    LegalBasis = "Companies Act 2014 — distributions and capital maintenance",
                    IsAuto = true,
                    CreatedBy = "System"
                });
            }
            else
            {
                adjustments.Add(new Adjustment
                {
                    PeriodId = periodId,
                    Description = $"Dividend declared and unpaid — source #{dividend.Id}",
                    DebitCategoryId = dividendsPaidId,
                    CreditCategoryId = dividendsPayableId,
                    Amount = dividend.Amount,
                    Source = AdjustmentSource.Auto,
                    Reason = "Declared distribution recognised as a liability until payment",
                    LegalBasis = "Companies Act 2014 — distributions and capital maintenance",
                    IsAuto = true,
                    CreatedBy = "System"
                });
            }
        }

        await AdjustmentPostingRules.ApplyDerivedImpactsAsync(db, adjustments);
        db.Adjustments.AddRange(adjustments);
        await db.SaveChangesAsync();

        // Record the actual capital allowance claimed against each asset this period so future
        // periods read the real cumulative claim rather than re-estimating it (BL-06).
        await new TaxComputationService(db, new FinancialStatementsService(db))
            .PersistCapitalAllowanceClaimsAsync(companyId, periodId);

        // Calculate summary
        var allAdjustments = await db.Adjustments.Where(a => a.PeriodId == periodId).ToListAsync();
        return new AdjustmentSummary(
            allAdjustments.Count(a => a.IsAuto),
            allAdjustments.Count(a => !a.IsAuto),
            allAdjustments.Count(a => a.ApprovedAt == null),
            allAdjustments.Count(a => a.ApprovedAt != null),
            allAdjustments.Sum(a => a.ImpactOnProfit),
            allAdjustments.Sum(a => a.ImpactOnAssets)
        );
    }

    // Length of an accounting period as a fraction of a 12-month year (capped at 1.0), used to
    // pro-rate a year's loan interest for short accounting periods.
    private static decimal PeriodYearFraction(DateOnly start, DateOnly end)
    {
        var days = end.DayNumber - start.DayNumber + 1;
        if (days <= 0) return 0m;
        return Math.Min(1m, days / 365m);
    }

    private static bool IsReversingBalanceJournal(Adjustment adjustment) =>
        adjustment.Description.StartsWith("Prepayment —", StringComparison.Ordinal)
        || adjustment.Description.StartsWith("Trade debtor —", StringComparison.Ordinal)
        || adjustment.Description.StartsWith("Accrual —", StringComparison.Ordinal)
        || adjustment.Description.StartsWith("Trade creditor —", StringComparison.Ordinal)
        || adjustment.Description.StartsWith("Director loan reclassification —", StringComparison.Ordinal)
        || adjustment.Description.Equals("Closing stock / inventory recognition", StringComparison.Ordinal);

    private static decimal ActualActualYearFraction(DateOnly start, DateOnly end)
    {
        if (end < start)
            return 0m;

        decimal fraction = 0m;
        var cursor = start;
        while (cursor <= end)
        {
            var segmentEnd = new DateOnly(cursor.Year, 12, 31);
            if (segmentEnd > end)
                segmentEnd = end;
            var days = segmentEnd.DayNumber - cursor.DayNumber + 1;
            fraction += days / (decimal)(DateTime.IsLeapYear(cursor.Year) ? 366 : 365);
            cursor = segmentEnd.AddDays(1);
        }

        return fraction;
    }

    private async Task<int> GetAssetCategoryIdAsync(int companyId, string assetCategory)
    {
        var code = assetCategory switch
        {
            "Land & Buildings" or "Property" => "0010",
            "Plant & Machinery" => "0020",
            "Motor Vehicles" or "Vehicles" => "0030",
            "Office Equipment" or "Equipment" or "Furniture" => "0040",
            "Computer Equipment" or "IT" => "0050",
            _ => "0040"
        };

        return await GetOrCreateCategoryIdAsync(companyId, code, assetCategory, AccountCategoryType.Asset, TaxTreatment.CapitalAllowance);
    }

    private async Task<int> GetExpenseCategoryForDescriptionAsync(int companyId, string description)
    {
        var lower = description.ToLowerInvariant();
        var (code, name) = lower switch
        {
            var text when text.Contains("interest") || text.Contains("loan") => ("6900", "Bank Charges & Interest"),
            var text when text.Contains("account") || text.Contains("audit") => ("6810", "Accountancy Fees"),
            var text when text.Contains("legal") || text.Contains("solicitor") => ("6820", "Legal Fees"),
            var text when text.Contains("insurance") => ("6200", "Insurance"),
            var text when text.Contains("electric") || text.Contains("heat") || text.Contains("light") => ("6300", "Light & Heat"),
            var text when text.Contains("phone") || text.Contains("internet") || text.Contains("vodafone") => ("6400", "Telephone & Internet"),
            var text when text.Contains("software") || text.Contains("subscription") => ("7300", "Software & Subscriptions"),
            var text when text.Contains("rent") => ("6100", "Rent"),
            _ => ("7900", "Sundry Expenses")
        };

        return await GetOrCreateCategoryIdAsync(companyId, code, name, AccountCategoryType.Expense, TaxTreatment.Deductible);
    }

    private async Task<int> GetOrCreateCategoryIdAsync(
        int companyId,
        string code,
        string name,
        AccountCategoryType type,
        TaxTreatment taxTreatment)
    {
        var category = await db.AccountCategories
            .FirstOrDefaultAsync(c => c.CompanyId == companyId && c.Code == code);

        if (category != null)
            return category.Id;

        category = new AccountCategory
        {
            CompanyId = companyId,
            Code = code,
            Name = name,
            Type = type,
            TaxTreatment = taxTreatment,
            IsSystem = true
        };
        db.AccountCategories.Add(category);
        await db.SaveChangesAsync();

        return category.Id;
    }
}
